network:
  version: 2
  renderer: NetworkManager

  ethernets:

    all-eths:
      match:
        name: eth*
      dhcp4: yes
      dhcp6: yes
      optional: true
  
  wifis:

    # standard Wi-Fi config (client)
    # ========================================
    wlan0:
      dhcp4: false
      dhcp6: true
      optional: true
      addresses: [192.168.100.ROBOT_IP/24]
      gateway4: 192.168.100.1
      access-points:
        "rmit-redbackbots":
          password: "rbb-a11l4b?!"
      nameservers:
        addresses: [10.68.196.1,10.84.196.1,8.8.8.8,4.4.4.4]

